### PR TITLE
Add GC5 workshop to events

### LINKED ISSUE #118: Add GC5 assessment workshop to events

### PR DESCRIPTION
**Pull request by MartinDix**
# ACCESS Community Hive 

Thank you for submitting a pull request to the ACCESS Hive Project. 

## Description

Add GC5 workshop to events page (assuming this page is meant to have content and not just a link).

Fixes #118

## Type of change

Please delete options that are not relevant.

- [x] New link / content

## Checklist:

- [x] The new content is accessible and located in the appropriate section.
- [x] My changes do not break navigation and do not generate new warnings
- [x] I have checked that the links are valid and point to the intended content.
- [x] I have checked my code/text and corrected any misspellings

Please tag the **reviewers team** in a comment below by prepending an `@` in front of `ACCESS-Hive/reviewers` when ready.

### CODE REVIEW

**Comment by MartinDix** [comment]
@ACCESS-Hive/reviewers

**Comment by ccarouge** [comment]
@MartinDix can you move the text to this file: docs/events/workshops.md

Otherwise, I'm still trying to work out why is the PR preview not working. I am worried it's because the PR is from a fork.

**Comment by ccarouge** [comment]
@MartinDix I'm trying to figure out what is going on with the preview. I see the pull request is from a fork in your GitHub account. I'm guessing you added the modification on GitHub and it created the fork for you? Did you have any option to create a branch instead of a fork?

**Comment by MartinDix** [comment]
I clicked on the edit button and it created a fork automatically (as also reported in #116). There was no option to do anything else.

Message at top of page says 

> You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork MartinDix/ACCESS-Hive, so you can send a pull request.

**Comment by MartinDix** [comment]
I completely missed the Conferences and Workshop links on the LHS which is why I added it to the main page. Perhaps these need to be bigger headings in the main body?

**Comment by ccarouge** [comment]
Or we could change the navigation:

- Events page (index.md) has the introduction and the list of all events
- Then a page for past events to keep links to material (published talks, summaries etc.)

**Comment by MartinDix** [comment]
Now added GC5 to the workshops page.

**Comment by rbeucher** [comment]
@MartinDix if you rebase on `main` the Preview should work now.

**Comment by ccarouge** [comment]
Can I bother you for a test? I've changed the action that builds the preview. Now the action should work from a fork but it won't try to build on creation of the PR but only when the PR gets a "safe to test" label. Only people with write access can add a label to a PR. 

So typically the idea is people open a PR from a fork, a reviewer checks the changes are safe, labels the PR and the reviewer can use the preview to make a proper review.

Could I try this with your proposed changes? For this, I need this PR to be closed I think. And your changes to be applied on top of the new HEAD of main, either:

- update your fork and rebase your branch
- or restart from updating the file on ACCESS-Hive, recreate a branch and PR.

**Comment by MartinDix** [comment]
I used "sync fork" in the branch on github. Does this work?

**Comment by ccarouge** [comment]
Yes, skipping on creation of the PR is intended. I've put the label on and now it is running the preview. But it failed again. :(

**Comment by ccarouge** [comment]
I forgot one change in the GitHub workflow for the preview but when I put it in it doesn't work in my PR #123 . I have tried in my personal account before and it worked fine, I'm still looking at what could be the issue here.

**Comment by ccarouge** [comment]
@MartinDix I've changed the CI again. Could you run a "sync fork" again please?

**Comment by rbeucher** [comment]
I am merging this so we can move on and work on refactoring the workshop/conference pages.

**Pull request merged**
