### PR TITLE
Merging Hubs

### LINKED ISSUE #91: Merge Hubs into one single entity

### PR DESCRIPTION
**Pull request by rbeucher**
# ACCESS Community Hub 

Merging Hubs...
Work in progress

Will close #91

### CODE REVIEW

**Comment by rbeucher** [comment]
@ccarouge 

Links are passing but we need to change the link to the NRI Hub...They won't work once deployed.

**Comment by rbeucher** [comment]
Actually the check links CI does not do anything

**Comment by ccarouge** [comment]
@rbeucher The new site doesn't have a direct link to the How to contribute guide, is that intentional? It's only accessible from the links in the front page now.

If we want to add it back, do we want to have a tab for it or put it under trainings? I'd vote for a tab.

**Comment by ccarouge** [comment]
I had a go mainly at populating the Configurations tab but with some updates on other pages too. This removes the need for the deprecated section I think.

**Pull request merged**
