### PR TITLE
Mock up of navigation structure for two sub-sites

### PR DESCRIPTION
**Pull request by aidanheerdegen**
Mock up to see how #35 looks but split into two separate sub-sites. Possible solution to #14

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
This doesn't work seamlessly currently due to a [bug/change in mkdocs](https://github.com/mkdocs/mkdocs/issues/2752#issuecomment-1243252361), relative URLs outside of the current site don't work, so the links from each of the sub-sites are broken, but you can view each separately

https://access-hub.github.io/ACCESS-Hub/pr-preview/pr-37/ACCESS-NRI/

https://access-hub.github.io/ACCESS-Hub/pr-preview/pr-37/Community/

The cross-links would work if it was deployed to the website.

**Comment by ccarouge** [comment]
I think that's the navigation that will work the best. I tried to see if we could simplify the navigation in the 1 site mockup but I don't think so.

**Comment by ccarouge** [comment]
@aidanheerdegen I'm not sure I follow the directory structure. 
We have:
- access-nri
  - docs
    - ACCESS-NRI
       - \<tab names\>

and
- docs
   - Community
      - \<tab names\>

Aren't the ACCESS-NRI and Community levels just before the folders for each tab redundant?

**Comment by aidanheerdegen** [comment]
I guess they are there as an artefact from the previous structure.

Yeah feel free to not use that structure.

**Comment by ccarouge** [comment]
Navigation is decided. Can close mock-up

**Pull request closed without merging**
